# Generated by Django 4.0.5 on 2022-07-12 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(max_length=50, unique=True)),
                ('video_path', models.CharField(max_length=400, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_dt', models.DateTimeField(auto_now_add=True)),
                ('translated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL)),
                ('word_translated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='words.word')),
            ],
        ),
    ]
